import { type AppType } from "next/dist/shared/lib/utils";
import "@/styles/globals.css";
import FooterComponent from "@/components/GeneralComponents/Footer";
import {GoogleOAuthProvider} from "@react-oauth/google";
import Head from "next/head";

const MyApp: AppType = ({ Component, pageProps }) => {

  return (

    <>
      <Head>
        <title>Flash Brain</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />
      </Head>
      <GoogleOAuthProvider clientId="341894606122-skvs01vfcnl2rd26jn591ko81j1r1csj.apps.googleusercontent.com">
        <div>
          <Component {...pageProps} />
          <FooterComponent />
        </div>
      </GoogleOAuthProvider>
    </>
      
  );
};

export default MyApp;
