import Head from "next/head";
import Header from "@/components/GeneralComponents/Header";
import useCheckLoggedIn from "@/utils/useCheckLoggedIn";
import config from "@/config";
import styles from '@/styles/index.module.css';
import router from "next/router";
import {useState} from "react";
import {Category} from "@/utils/model/Category";

function categoryList(props: any) {

    let categories: Category[] = [
        {categoryName: "All", categoryId: 0},
        {categoryName: "Math", categoryId: 1},
        {categoryName: "Science", categoryId: 2},
        {categoryName: "Cinema", categoryId: 3},
        {categoryName: "Other", categoryId: 4},

    ]
    const categoryList = props.categoryList;
    const setCategoryList = props.setCategoryList;

}

export default function Home() {

  const {isLoggedIn, isPending: isPendingLoggedIn} = useCheckLoggedIn();
  const [activeCategoryList, setActiveCategoryList] = useState<number[]>([]);

    function scrollToSection(id:string) {
        const section = document.getElementById(id);
        if (section) {
            section.scrollIntoView({ behavior: 'smooth' });
        }
    }

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <>
          <div className={styles.indexOuterDiv}>
              <Header></Header>
              <div className={styles.indexContentDiv}>
                <div className={styles.indexHigherDiv}>
                    <div className={styles.indexHigherDivLeft}>
                        <p className={styles.indexMotto}>Make hard things<br/> easy to understand</p>
                        <div>
                            {!isLoggedIn && <button className="big-btn" onClick={() => router.push('/register')}>Register now</button>}
                            {isLoggedIn && <button className="big-btn" onClick={() => scrollToSection("browseSection")}>Get started</button>}
                        </div>
                    </div>
                    <div className={styles.indexHigherDivRight}>
                        <div className={styles.circle1}></div>
                        <div className={styles.circle2}></div>
                        <div className={styles.circle3}></div>
                    </div>
                </div>
                  <section id="browseSection">
                      <div className={styles.indexLowerDiv}>
                          <form className={styles.indexSearchForm}>
                            <div className={styles.searchBarDiv}>
                                <input type="text" className={styles.searchBarInput}></input>
                                <button className={styles.searchBarButton}>Search</button>
                            </div>
                          </form>
                      </div>
                  </section>
              </div>
          </div>


      </>
    </>
  );
}
